package:
  name: oracle-instant-client
  version: {{ '19.16.0.0.0' if osx else '23.8.0.25.04' }}

source:
  path: instantclient-basic-linux.arm64-23.8.0.25.04.zip

build:
  binary_relocation: false
  number: 6
  skip: true  # [not unix]
  runpath_whitelist:
    - ../lib
  missing_dso_whitelist:
    - /lib64/libdl.so.2  # [linux]
    - /lib64/libm.so.6  # [linux]
    - /lib64/libpthread.so.0  # [linux]
    - /lib64/librt.so.1  # [linux]
    - /lib64/libresolv.so.2  # [linux]
    - /lib64/libc.so.6  # [linux]
    - /lib64/ld-linux-x86-64.so.2  # [linux]
    - /lib64/libstdc++.so.6  # [linux and aarch64]
    - /lib64/libgcc_s.so.1  # [linux and aarch64]

    - $RPATH/libdl.so.2  # [linux]
    - $RPATH/libm.so.6  # [linux]
    - $RPATH/libpthread.so.0  # [linux]
    - $RPATH/librt.so.1  # [linux]
    - $RPATH/libresolv.so.2  # [linux]
    - $RPATH/libc.so.6  # [linux]
    - $RPATH/ld-linux-x86-64.so.2  # [linux]
    - $RPATH/libstdc++.so.6  # [linux]
    - $RPATH/libgcc_s.so.1  # [linux]

    - $RPATH/libaio.so.1  # [linux]

  ignore_run_exports:
    - libaio

requirements:
  build:
    - unzip
  host:
    - libaio {{ libaio }}  # [linux]
    # - patchelf  # [linux]
  run:
    - curl
    - libaio  # [linux]
    - unzip
    - __glibc >=2.28  # [linux]
    - libgcc-ng >=11.2.0 # [linux]
    - openjdk
test:
  files:
    - tests/test.py
    - tests/cdemo81
  requires:
    - python
    - oracledb
    - pytest
    - patchelf
  commands:
    - echo "It works!"
#    - echo "testing with python!"
#    - python tests/test.py
#    - echo "tested with python!"
#    - test -f ${PREFIX}/oracle_instant_client/instantclient_*/CONDA_LINKS
#    - patchelf --set-rpath $CONDA_PREFIX/lib tests/cdemo81
#    - echo "ldLibPath is $LD_LIBRARY_PATH"
#    - patchelf --set-rpath '$ORIGIN/../lib' tests/cdemo81
#    - tests/cdemo81
    - echo "CONDA_PREFIX is $CONDA_PREFIX"
    - echo "PREFIX is $PREFIX"
    - pytest -vv -s tests/test.py

about:
  home: https://www.oracle.com/database/technologies/instant-client.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: package to download and install oracle instant client
  description: |
    This package downloads and installs the Oracle Instant Client. By default, it uses a standard location.

    If you're behind a firewall and unable to download the instant client zip file from download.oracle.com,
    you can set the environment variable `ORACLE_DOWNLOAD_BASE_URL` to specify where it should look for the
    corresponding zip file. The zip file must have the same name as found on the oracle website: 
    https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html.

    ```bash
    export RACLE_DOWNLOAD_BASE_URL=https://my.internal.website/oracle
    conda install oracle-instant-client
    ```  

extra:
  recipe-maintainers:
    - beckermr
