package:
  name: oracle-instant-client
  version: {{ '19.8.0.0.0' if osx else '23.7.0.25.01' }}

source:
  path: .

build:
  number: 4
  skip: true  # [not unix]

requirements:
  host:
  run:
    - curl
    - unzip
    - __glibc >=2.28  # [linux]

test:
  commands:
    - echo "It works!"
    - test -f ${PREFIX}/oracle_instant_client/instantclient_*/CONDA_LINKS

about:
  home: https://www.oracle.com/database/technologies/instant-client.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: package to download and install oracle instant client

extra:
  recipe-maintainers:
    - beckermr
