package:
  name: oracle-instant-client
  version: {{ '19.8.0.0.0' if osx else '23.7.0.25.01' }}

source:
  path: .

build:
  number: 5
  skip: true  # [not unix]

requirements:
  host:
  run:
    - curl
    - libaio
    - unzip
    - __glibc >=2.28  # [linux]

test:
  commands:
    - echo "It works!"
    - test -f ${PREFIX}/oracle_instant_client/instantclient_*/CONDA_LINKS

about:
  home: https://www.oracle.com/database/technologies/instant-client.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: package to download and install oracle instant client
  description: |
    This package downloads and installs the Oracle Instant Client. By default, it uses a standard location.

    If you're behind a firewall and unable to download the instant client zip file from download.oracle.com,
    you can set the environment variable `ORACLE_DOWNLOAD_BASE_URL` to specify where it should look for the
    corresponding zip file. The zip file must have the same name as found on the oracle website: 
    https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html.

    ```bash
    export ORACLE_DOWNLOAD_URL=https://my.internal.website/oracle
    conda install oracle-instant-client
    ```  

extra:
  recipe-maintainers:
    - beckermr
